services:
  notes:
    build: .
    container_name: notes
    ports:
      - $PORT:$PORT
    environment:
      - PORT
      - STATE_DIR=/var/lib/notes
    image: lucas42/lucos_notes
    volumes:
      - stateFile:/var/lib/notes
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:${PORT}/_info"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

volumes:
  stateFile: