version: 2.1
orbs:
  lucos: lucos/deploy@0

jobs:
  test:
    docker:
      - image: node:16-alpine
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm i
      - run:
          name: Run Tests
          command: npm test
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - lucos/build-amd64:
          context: docker
      - lucos/deploy-avalon:
          context: docker
          requires:
            - test
            - lucos/build-amd64
          filters:
            branches:
              only:
                - main